replicaCount: 2

image: 
  name: XXXXXXXX.dkr.ecr.XXXXXXXXXX.amazonaws.com/XXXXXXXXXX
  tag: latest


serviceType: LoadBalancer
serviceListenerPort: 80
serviceTargetPort: 8080

secretName: database-credentials-helm
secretType: Opaque
secretApplicationProperties: |-
  database=XXXXXXXXX
  spring.datasource.url=XXXXXXXXXXXXXXXXXXXXXXXXXX
  spring.datasource.username=XXXXXXXX
  spring.datasource.password=XXXXXXXXX
  spring.sql.init.mode=always


appName: petclinic-helm-2

volume:
  name: db-credentials
  mountPath: /mnt

namespace: majd-ns
