apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  application-mysql.properties: | 
  {{- .Values.secretApplicationProperties | nindent 4  }}