apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-loadbalancer
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.serviceListenerPort }}
      targetPort: {{ .Values.serviceTargetPort }}